[package]
name = "faelight-term"
version = "8.0.0"
edition = "2021"

[dependencies]
smithay-client-toolkit = "0.20"
wayland-client = "0.31"
fontdue = "0.9"
nix = { version = "0.29", features = ["term", "process", "fs"] }
calloop = "0.14"
calloop-wayland-source = "0.4"
