[package]
name = "faelight-term"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
wayland-client.workspace = true
smithay-client-toolkit.workspace = true
fontdue.workspace = true
vte.workspace = true
nix.workspace = true
