[package]
name = "recent-files"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
walkdir = "2.5"
chrono = "0.4"
colored = "2.1"
clap = { version = "4.5", features = ["derive"] }
