[package]
name = "faelight-lock"
version = "0.2.0"
edition = "2021"
description = "Faelight Forest screen locker"

[dependencies]
faelight-core = { path = "../faelight-core" }

[profile.release]
opt-level = "z"
lto = true
strip = true
